### PR TITLE
Support Intellij Plugin 2.x

### LINKED ISSUE #1: Incompatible with the latest version of Rider
Thanks for your great plugin. 

I recently upgraded to 2024.2 of Rider and the plugin is complaining that is requires IDE build 241.* or earlier.

Do you have any plans to support this version?

### PR DESCRIPTION
**Pull request by wQuasar**
- Add support for Intellij plugin 2.x
- Update Kotlin version to "2.0.20"
- Update the 'untilBuild' version to "242.*"

Fixes #1 , #2 .

### CODE REVIEW

**Comment by baynezy** [comment]
@wQuasar - thanks for doing this. Do you have plans to release a new version to the marketplace?

**Comment by wQuasar** [comment]
Hello @baynezy . I've already submitted the build to the marketplace for approval last night. They usually take up to 2 business days to approve a release so, the new version should be live in about 24 to 36 hours (or maybe any second now :D). 

I'll ping here once the update is generally available.

**Comment by wQuasar** [comment]
Hello @baynezy . Thanks for reporting this! Version "0.6.2" is now available in the marketplace.

**Comment by baynezy** [comment]
Thanks. I just updated it. Works a treat.

**Pull request merged**
